import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { isAdmin } from "../../server/common/requireAuth";
import { trpc } from "../../utils/trpc";
import { useRouter } from "next/router";
import { useEffect } from "react";

export const getServerSideProps = isAdmin(async () => {
    return { props: {} };
});

function Dashboard () {
  const router = useRouter();
  const { data:session } = useSession();
  const {data} = trpc.user.me.useQuery();
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Dashboard | {session?.user?.name}</h1>
      </main>
    </>
  );
};

export default Dashboard;
