import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { requireAuth } from "../../server/common/requireAuth";

export const getServerSideProps = requireAuth(async () => {
    return { props: {} };
});

const Dashboard: NextPage = () => {
    const { data } = useSession();
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white">Dashboard | {data?.user?.name}</h1>
      </main>
    </>
  );
};

export default Dashboard;
