import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { trpc } from "../utils/trpc";
import { toast } from 'react-toastify';
import Link from "next/link";
interface UserSign {
  email: string;
  firstname: string;
  lastname: string;
  password: string;
}

const SignUp: NextPage = () => {
  const router = useRouter();
  const [data, setData] = useState<UserSign>({
    email: "",
    firstname: "",
    lastname: "",
    password: "",
  })
  const { mutateAsync } = trpc.user.signup.useMutation();
  return (
    <div>
      <Head>
        <title>Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form
          className="flex items-center justify-center h-screen w-full"
          onSubmit={(event) => {
            event.preventDefault();
            mutateAsync({
              email: data.email,
              firstname: data.firstname,
              lastname: data.lastname,
              password: data.password,
            })
             .then((res) => {
              toast.success(res.message);
              setData({
                email: "",
                firstname: "",
                lastname: "",
                password: "",
              })
              router.push("/login")
            })
             .catch((err) => toast.error(err.message))
          }}
          >
          <div className="p-2 border">
            <div className="flex flex-col items-center justify-center">
              <h2 className="card-title">Create an account!</h2>
              <input 
              type="text"
              className="p-2 border w-full m-2"
              placeholder="Email"
              value={data.email} 
              onChange={(e) => setData({...data, email: e.target.value })} 
              />
              <input 
              type="text"
              className="p-2 border w-full m-2"
              placeholder="Firstname"
              value={data.firstname} 
              onChange={(e) => setData({...data, firstname: e.target.value })} 
              />
              <input 
              type="text"
              className="p-2 border w-full m-2"
              placeholder="Lastname"
              value={data.lastname} 
              onChange={(e) => setData({...data, lastname: e.target.value })} 
              />
              <input 
              type="text"
              className="p-2 border w-full m-2"
              placeholder="Password"
              value={data.password} 
              onChange={(e) => setData({...data, password: e.target.value })} 
              />
              <div className="w-full p-2">
                <button className="p-2 bg-blue-800 text-white w-full" type="submit">
                  Sign Up
                </button>
                
              </div>
              <div className="w-full p-2">
                <Link href="/login">
                  <button className="p-2 bg-blue-800 text-white w-full" type="submit">
                    Login
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default SignUp;
