import React from 'react'

function HeadCustom({title}) {
  return (
    <div>
        <Head>
            <title>{title} | COMPANY</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    </div>
  )
}

export default HeadCustom